services:
  - type: web
    name: frontend-challenge-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn server.asgi:application -k uvicorn.workers.UvicornWorker --log-file -
    envVars:
      - key: DJANGO_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: frontend-challenge-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: https://your-frontend-domain.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://your-frontend-domain.com

databases:
  - name: frontend-challenge-db
    plan: free
